name: 'Strava Swagger to Pydantic'
description: 'Creates Pydantic model in given target directory'
inputs:
  model_file:
    description: 'Target module filename for model'
    required: true
    default: 'strava_model.py'
runs:
  using: 'composite'
  steps:
    - name: Pass Inputs to Shell
      run: echo "MODEL_FILE=${{ inputs.model_file }}" >> $GITHUB_ENV
      shell: bash
    - name: Checkout
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        repository: stravalib/strava_swagger2pydantic
        path: model_generator
    - name: Install Python
      uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
      with:
        python-version: '3.10'
    # Install uv for dependency management
    - name: Setup uv
      uses: astral-sh/setup-uv@v6
    # Cache uv package downloads to speed up subsequent runs
    - name: Set Cache Variables
      id: cache_variables
      shell: bash
      run: |
        echo "PY=$(python -c 'import hashlib, sys;print(hashlib.sha256(sys.version.encode()+sys.executable.encode()).hexdigest())')" >> $GITHUB_OUTPUT
        echo "UV_CACHE=${HOME}/.cache/uv" >> $GITHUB_OUTPUT
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: ${{ steps.cache_variables.outputs.UV_CACHE }}
        key: ${{ steps.cache_variables.outputs.PY }}
    # Install exactly what's in uv.lock
    - name: Install Dependencies (locked)
      run: uv sync --locked
      shell: bash
    - name: Generate Model
      run: uv run python model_generator/swagger2pydantic.py
      shell: bash
